### ISSUE TITLE
concestor

### ISSUE THREAD

**Issue by dominictarr** [substack/forkdb#4]
It would be awesome to have a concestor function, "concestor" is a biology term that means "common ancestor". getting the common ancestor of the heads would be very awesome, because it would be possible to do a 3-way merge like in git.

incidentially, here is some 3-way merge code I prepared earlier, although there are other diff modules on npm too. https://github.com/dominictarr/adiff

**Comment by substack** [comment]
Implemented in 9.1.0:

```
$ forkdb -d /tmp/a future 6f5f5c0eb9eddad82def36df325eb61ed4d552bf765a2cebb3ebfd98d4d5181d
+- wow :: 6f5f5c0eb9eddad82def36df325eb61ed4d552bf765a2cebb3ebfd98d4d5181d
|- wow :: 949290ad26e9a35f48ceb0935266d4bc10395f62aac7650fe356c5ff798e698a
 +- wow :: 3121f5cf72b54e295b71964c8250f586090bede4e715ff0052ef14f16b93a982
 |- wow :: f9d9f677889418d20aaa3c50746e97ccaf1246e0c74ec0a5a0bc9a38e06921be
 +- wow :: 3f60dc6c0ea9f2be3be20718f60a66a6737db47aa79134bb3e444a0d488c2816
 |- wow :: 50fc7eabaec54a217b987bfa999e7a95f40e88146372e8352c06ad6d73b571be
  +- wow :: 26ff64941c3c376f6d0762932c2464c5218d659d04dca734052b87b76724546b
  +- wow :: 7644743f2f31144326cd666be8a99c9baa3c0f98863cbf0e67929efa17015d44
$ forkdb -d /tmp/a concestor 7644743f2f31144326cd666be8a99c9baa3c0f98863cbf0e67929efa17015d44 26ff64941c3c376f6d0762932c2464c5218d659d04dca734052b87b76724546b
50fc7eabaec54a217b987bfa999e7a95f40e88146372e8352c06ad6d73b571be
$ forkdb -d /tmp/a concestor 7644743f2f31144326cd666be8a99c9baa3c0f98863cbf0e67929efa17015d44 26ff64941c3c376f6d0762932c2464c5218d659d04dca734052b87b76724546b f9d9f677889418d20aaa3c50746e97ccaf1246e0c74ec0a5a0bc9a38e06921be
949290ad26e9a35f48ceb0935266d4bc10395f62aac7650fe356c5ff798e698a
```

I'm also planning on using concestor with that adiff module for [shipboard](https://github.com/substack/shipboard).

**Comment by ekg** [comment]
I'd never heard of "concestor" before (and I work in genomics!). Is this a Richard Dawkins meme? :) "Common ancestor" is standard in biology, and is almost always qualified further when precision is needed. Is it the most-recent ancestor, or just any random one that you are going for?

**Comment by dominictarr** [comment]
@ekg yeah looks like it. I was working on this in the library and I opened a book randomly and learnt that word, which was exactly what I was looking for. https://en.wiktionary.org/wiki/concestor

It's the most recent ancestor.
