### ISSUE TITLE
you left index.js out of the last forkdb release

### ISSUE THREAD

**Issue by heavyk** [substack/forkdb#6]
just lettin' ya know.

the concept is so far out, man.... it's been blowin my mind just rethinking history as a series of improvements on previous content.

the absolutely crazy bit is it's exactly the same thing as parent child way of looking at it but it feels like a spring breeze in my hair instead of the growing responsibility...

three thumbs up dude!

**Comment by jesstelford** [comment]
Until this is fixed, you can get around it by installing the previous version:

```bash
npm install --save forkdb@7.0.0
```

**Comment by substack** [comment]
All fixed! It was that npm bug I have been hitting all over the place.
